baseURL = 'https://tinyroosters.com'
languageCode = 'en-us'
title = 'Tiny Roosters'
enableGitInfo = true

[taxonomies]
  tag = "tags"
  category = "categories"
  project_tag = "project_tags"

[params]
  description = "Welcome to Tiny Roosters! Here you'll find games & other programming projects, updates, and maybe more."
  images = ["images/splash_logo_primary.webp"]

[params.analytics.umami]
  enabled = true
  url = "https://cloud.umami.is/script.js"
  website_id = "92c79604-c335-40b6-b364-a8be1019aa33"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[markup]
  [markup.highlight]
    noClasses = false

[menus]
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    url = '/about'
    weight = 10
  [[menus.main]]
    name = 'Projects'
    pageRef = '/projects'
    url = '/projects'
    weight = 20
  [[menus.main]]
    name = 'Logs'
    pageRef = '/logs'
    url = '/logs'
    weight = 30
  [[menus.main]]
    name = 'Changelog'
    pageRef = '/changelog'
    url = '/changelog'
    weight = 40