name: Build and Deploy

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: false

    - name: Build Hugo site
      run: hugo --minify

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
        aws-region: ${{ vars.AWS_REGION }}

    - name: Sync files to S3
      run: |
        aws s3 sync ./public/ s3://${{ vars.S3_BUCKET }} --delete

    - name: Invalidate CloudFront Cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.AWS_CLOUDFRONT_ID }} \
          --invalidation-batch '{
              "Paths": {
                  "Quantity": 1,
                  "Items": [
                      "/*"
                  ]
              },
              "CallerReference": "${{ github.sha }}"
          }'
